theme: jekyll-theme-cayman
title: MESMerizing Engineer
description: Autonomous Inspection Robot

link: https://mesmerizing-engineers.github.io/MESMerizing-Engineers/about

# Site navigation links
- title: Home
  url: /

- title: About
  url: /about/

- title: Test
  url: /test/

- title: index
  url: /index/
